const TRENDING_CONTENT = [
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    distance: "3.2 km",
    imageURL: "https://picsum.photos/200/100",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Arup Dhodi",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    imageURL: "https://picsum.photos/200/100",
    id: "23423",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
];

const POSTS_CONTENT = [
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800/400",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.A short travel package without any hassel. Spend weekens in a very reasonable price.A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800/400",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800/400",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800/400",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
  {
    profile: {
      name: "Rudrakaal",
      followers: "1.2M",
      following: "1.2M",
      imageURL: "https://picsum.photos/100/100",
      distance: "3.2 km",
      id: "23423",
    },
    shopURL: "/post/23423",
    post: {
      imageURL: "https://picsum.photos/800/400",
      description:
        "A short travel package without any hassel. Spend weekens in a very reasonable price.",
      liked: true,
      likes: "72",
      comments: "10",
      shares: "2",
    },
    liked: true,
  },
];

const LOCAL_MARKET_CONTENT = [
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    distance: "3.2 km",
    location: "Delhi",
    imageURL: "https://picsum.photos/200/100",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    location: "Delhi",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    location: "Delhi",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    location: "Delhi",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
    location: "Delhi",
  },
  {
    name: "Preeti Desai",
    designation:
      "Brand Ambassador Brand Ambassador Brand Ambassador Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    location: "Delhi",
    liked: true,
  },
  {
    name: "Arup Dhodi",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
    location: "Delhi",
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    imageURL: "https://picsum.photos/200/100",
    id: "23423",
    distance: "3.2 km",
    liked: true,
    location: "Delhi",
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
    location: "Delhi",
  },
  {
    name: "Manav Singla",
    designation: "Brand Ambassador",
    company: "Ustra",
    id: "23423",
    imageURL: "https://picsum.photos/200/100",
    distance: "3.2 km",
    liked: true,
    location: "Delhi",
  },
];

export { TRENDING_CONTENT, POSTS_CONTENT, LOCAL_MARKET_CONTENT };
